### ISSUE TITLE
Broken Post Navigation

### ISSUE THREAD

**Issue by kkch** [ParitoshBh/grav-coder#18] opened 2019-11-10 22:51 UTC
broken post navigation, prevSibling() and nextSibling() render current post url.

**Comment by ParitoshBh** [comment] 2019-11-21 15:11
Can you please share Grav version you are using?

**Comment by HymieAli** [comment] 2020-01-11 10:50
I am actually having the same issue.
Tried upgading to the pre-release 1.7 version and it persisted as well.
I have just unzipped a new install into the directory and configured the settings per the write up. 

www.hymieali.com is the url, I can give you ftp access to the site if that helps
Grav v1.6.19 - Admin v1.9.12 
Grav-Coder theme 0.1.6

**Comment by HymieAli** [comment] 2020-01-12 10:49
Did a little more testing to see if I could narrow it down a bit. Im not that fluent in the language but it was worth a try.

I took a peek at the pagination area
 {% if itemsInCollection > itemsPerPage %} , and tried adding the pages into a collection using a few methods as well as the @self.children and the call to page.prevSibling.url is still returning the current page. 

I tried commenting out the if not page is Last/First to see if it would force it, but it didnt change so I reverted it.

I tried adding the call to page.adjacentSibling(-1) instead of the page.previous.sibling and opened a page in the middle of the collection. No change.
I also tried page.prevSibling(page.path).title with no change.
Since each of these are reliant on the collection feature working, perhaps there is something in my install that is failing to create them for this one folder. I will test a bit more and update if I get anywhere.

-Ali

**Comment by Bobblejot** [comment] 2020-03-08 17:29
Hi did anyone discover the cause of this issue?  i am having exactly the same problem.  Previous and next links just link to the post your on.

**Comment by HymieAli** [comment] 2020-03-08 20:38
I was not able to get it working myself. As a workaround I just have a block of text I put in at the end of each post that has a link to go back to the main blog listing.

**Comment by Bobblejot** [comment] 2020-03-08 22:00
HymieAli - thanks for the reply been around the houses myself trying everything i could find without much luck, hopefully it will get fixed at some point.

**Comment by ParitoshBh** [comment] 2020-03-08 22:04
Sorry guys, I have been busy with my day job recently. I have planned to devote some time for this bug today. Will update if more information is required.

**Comment by ParitoshBh** [comment] 2020-03-08 22:38
> [www.hymieali.com](http://www.hymieali.com) is the url, I can give you ftp access to the site if that helps
> Grav v1.6.19 - Admin v1.9.12
> Grav-Coder theme 0.1.6

Will you be able to share the zip of your root directory or ftp access? I am not able to reproduce the problem both of you are facing and clearly there's something in your setup that isn't in mine.

**Comment by HymieAli** [comment] 2020-03-08 22:49
you bet, fire me an email and Ill reply with some temp credentials to login via ftp
hymie@hymieali.com

**Comment by ParitoshBh** [comment] 2020-03-08 22:58
Sent you an email just now :)

**Comment by ParitoshBh** [comment] 2020-03-10 01:43
Pushed [release 0.1.7](https://github.com/ParitoshBh/grav-coder/releases/tag/0.1.7) hoping to fix this. Please update and test to see if fix works.

**Comment by HymieAli** [comment] 2020-03-10 02:11
Pulled the zip file down, extracted it, renamed the old grav-coder to -old, put the new folder in place, re-enabled pagination in the grav-coder.yaml file, cleared cash and its working.
Testing first/last page and they show a single arrow as expected and all the rest click to previous/next posts.

Nice!

**Comment by ParitoshBh** [comment] 2020-03-10 02:13
Sweet! I'll close this issue then :)

**Closed by ParitoshBh** 2020-03-10 02:13 UTC
Labels: need-more-info
