### ISSUE TITLE
Content is load 'sideways'

### ISSUE THREAD

**Issue by tomlawesome** [ParitoshBh/grav-coder#28] opened 2021-11-08 13:45 UTC
Hello, firstly -- thank you for porting & modifying such a fabulous theme! It's great. 

I'm struggling to move my site to the theme though, because all the markdown content in page loads sideways? 

![image](https://user-images.githubusercontent.com/76453276/140744628-9b5d050a-03df-4a83-894f-82455511bd1c.png)

![image](https://user-images.githubusercontent.com/76453276/140744738-bc85f22e-74ee-43b9-950d-e4db1a3e4868.png)

**Comment by ParitoshBh** [comment] 2021-11-12 13:52
Did you try putting content in div? Homepage is special and you need to follow the structure that's provided.

**Comment by ParitoshBh** [comment] 2023-02-20 18:47
Closing this issue due to non-activity. If you still have the issue please re-open it (with details for reproducing).

**Closed by ParitoshBh** 2023-02-20 18:47 UTC
